/**
 * COCO 80クラスのラベル名（Ultralytics の学習時クラス順序、`data/coco.yaml` の `names` と同じ順）。
 *
 * YOLO11n-seg（issue #49, 親 #45）は COCO の80クラスのみで学習された閉集合検出器で、
 * これ以外のクラスは検出できない（issue #49 やってはいけないこと）。出力の class index
 * (0-79) をこの配列で人間可読なラベルへ変換する。
 */
export const COCO_CLASSES: readonly string[] = [
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "backpack",
  "umbrella",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "dining table",
  "toilet",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
];

/** COCO クラス数（80）。`4 + COCO_CLASS_COUNT + maskCoeffCount(32) = 116` が output0 の第2次元。 */
export const COCO_CLASS_COUNT = COCO_CLASSES.length;
